"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var movieController_1 = require("../controllers/movieController");
var router = (0, express_1.Router)();
router.get('/', movieController_1.getAllMovies);
router.post('/', movieController_1.createMovie);
router.put('/:id', movieController_1.updateMovie);
router.delete('/:id', movieController_1.deleteMovie);
exports.default = router;
